### ISSUE TITLE
Exception raised

### ISSUE THREAD

**Issue by schollii** [Ianyliu/blast-radius-fork#20]
Latest version installed just now per your instructions in Readme using pip

Platform: Ubuntu 20, python 3.8, terraform 1.2.7

Ran with `~/.local/bin/blast-radius --serve .` where . is an terraform init'ed folder
```
$ ~/.local/bin/blast-radius --serve .
 * Serving Flask app 'blastradius.server.server' (lazy loading)
 * Environment: production
   WARNING: This is a development server. Do not use it in a production deployment.
   Use a production WSGI server instead.
 * Debug mode: off
 * Running on all addresses (0.0.0.0)
   WARNING: This is a development server. Do not use it in a production deployment.
 * Running on http://127.0.0.1:5000
 * Running on http://10.0.2.15:5000 (Press CTRL+C to quit)
Blast Radius is generating graphs for your Terraform directory. 
127.0.0.1 - - [22/Sep/2022 04:48:07] "GET / HTTP/1.1" 200 -
127.0.0.1 - - [22/Sep/2022 04:48:07] "GET /static/js/jquery.slim.min.js HTTP/1.1" 200 -
127.0.0.1 - - [22/Sep/2022 04:48:07] "GET /static/js/bootstrap.min.js HTTP/1.1" 200 -
127.0.0.1 - - [22/Sep/2022 04:48:07] "GET /static/js/fontawesome-all.min.js HTTP/1.1" 200 -
127.0.0.1 - - [22/Sep/2022 04:48:07] "GET /static/js/d3.v4.js HTTP/1.1" 200 -
127.0.0.1 - - [22/Sep/2022 04:48:07] "GET /static/js/blast-radius.js HTTP/1.1" 200 -
127.0.0.1 - - [22/Sep/2022 04:48:07] "GET /static/js/d3-tip.js HTTP/1.1" 200 -
127.0.0.1 - - [22/Sep/2022 04:48:07] "GET /static/js/categories.js HTTP/1.1" 200 -
127.0.0.1 - - [22/Sep/2022 04:48:07] "GET /static/css/bootstrap.min.css HTTP/1.1" 200 -
127.0.0.1 - - [22/Sep/2022 04:48:07] "GET /static/css/style.css HTTP/1.1" 304 -
127.0.0.1 - - [22/Sep/2022 04:48:07] "GET /static/css/selectize.css HTTP/1.1" 200 -
127.0.0.1 - - [22/Sep/2022 04:48:07] "GET /static/js/svg-pan-zoom.js HTTP/1.1" 200 -
127.0.0.1 - - [22/Sep/2022 04:48:07] "GET /static/js/selectize.js HTTP/1.1" 200 -
[2022-09-22 04:48:17,953] ERROR in app: Exception on /graph.svg [GET]
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/lark/parsers/lalr_parser.py", line 59, in get_action
    return states[state][token.type]
KeyError: '__ANON_3'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 2077, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 1525, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 1523, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 1509, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/home/devops/.local/lib/python3.8/site-packages/blastradius/server/server.py", line 134, in graph_svg
    dot = initalizeDotGraph(content=run_tf_graph(),
  File "/home/devops/.local/lib/python3.8/site-packages/blastradius/server/server.py", line 215, in initalizeDotGraph
    tf = Terraform(os.getcwd())
  File "/home/devops/.local/lib/python3.8/site-packages/blastradius/handlers/terraform.py", line 29, in __init__
    self.config = hcl.load(config_io)
  File "/usr/local/lib/python3.8/site-packages/hcl2/api.py", line 9, in load
    return loads(file.read())
  File "/usr/local/lib/python3.8/site-packages/hcl2/api.py", line 18, in loads
    return hcl2.parse(text + "\n")
  File "/usr/local/lib/python3.8/site-packages/lark/lark.py", line 464, in parse
    return self.parser.parse(text, start=start)
  File "/usr/local/lib/python3.8/site-packages/lark/parser_frontends.py", line 115, in parse
    return self._parse(token_stream, start)
  File "/usr/local/lib/python3.8/site-packages/lark/parser_frontends.py", line 63, in _parse
    return self.parser.parse(input, start, *args)
  File "/usr/local/lib/python3.8/site-packages/lark/parsers/lalr_parser.py", line 35, in parse
    return self.parser.parse(*args)
  File "/usr/local/lib/python3.8/site-packages/lark/parsers/lalr_parser.py", line 88, in parse
    action, arg = get_action(token)
  File "/usr/local/lib/python3.8/site-packages/lark/parsers/lalr_parser.py", line 66, in get_action
    raise UnexpectedToken(token, expected, state=state, puppet=puppet)
lark.exceptions.UnexpectedToken: Unexpected token Token('__ANON_3', 'terraform') at line 109, column 3.
Expected one of: 
	* __ANON_2
	* __ANON_0
	* __ANON_1

127.0.0.1 - - [22/Sep/2022 04:48:17] "GET /graph.svg HTTP/1.1" 500 -
```

**Comment by Ianyliu** [comment]
It seems like the problem occurred when parsing the HCL files from a remote repository. The code responsible for the parsing of HCL files was passed down from the original repo. I'll see what I can do about it, but I've never touched the HCL parsing package before, so I can't guarantee anything.....

**Comment by Ianyliu** [comment]
Hi @schollii, 
Could you please test out this new change I made to the dev branch? It should resolve the problems for remote modules
I integrated changes from [Jrc356/blast-radius](https://github.com/Jrc356/blast-radius/commit/1d56a88d1bab81f5d031676c468a61171371ab10)

You can install via: 
`pip install -U git+https://github.com/Ianyliu/blast-radius-fork@dev`

**Comment by schollii** [comment]
Sure, ping me if I haven't posted results by Tuesday morning.

**Comment by Ianyliu** [comment]
Hi @schollii, any results yet?

**Comment by schollii** [comment]
It works now, thanks!

**Comment by schollii** [comment]
However there are some issues: 
- notice the duplicate "var" and "terraform" items in the box that appears when hover mouse over item:
![image](https://user-images.githubusercontent.com/2598808/196857053-95344a8e-565c-4cbb-bcb1-79923ff74580.png)
- when only json is checked in tooltip options, hover over box shows gray rectangle with no text (json should appear)
- when none of the tooltip options are checked, hover shows gray rectangle with no text (nothing should appear since none of the options are checked)
- I cannot type in the search box at top left, I can only select items; I should be able to type letters and it should highlight all the matches in the graph; actually a regexp would be best
- it looks like the graph renders differently everytime I go back to "whole graph view", it's like the auto-layout is not deterministic
- could you add ability to collapse and expand modules? 
- could you add option to group items by module? (graphviz supports grouping)

**Comment by Ianyliu** [comment]
I see, thank you for the feedback!

**Comment by Ianyliu** [comment]
@schollii 
Since I major in data science, less of my work will be related to this and therefore I have to inform you that I will not be able to spend as much time on this. 

I'm really thankful for the features you've suggested, and maybe when I have time during break I can try implementing them, but as of now, I will have to put it off to the side.
